{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lmaobgd.fullname" . | quote }}
  labels:
    app: {{ include "lmaobgd.name" . | quote }}
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql-postgres-password: {{ .Values.externalDatabase.superPassword | b64enc | quote }}
  postgresql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
